name: Android CI and CD
on:
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:
  build:
    runs-on:
       - ubuntu-latest
    steps:
     - name : Check out Git Repository
       uses: actions/checkout@v3

     - name: set up JDK 11
       uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'temurin'
         cache: gradle
          
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
      
     - name: Gradle Clean
       run: ./gradlew clean
      
     - name: Gradle Lint
       run: ./gradlew lint
      
     - name: Gradle Build and generating apk files
       run: ./gradlew build
      
     - name: Copy APK files to a directory
       run: |
          mkdir -p apk-files/debug apk-files/release
        
          cp ${{ github.workspace }}/app/build/outputs/apk/debug/app-debug.apk ${{ github.workspace }}/apk-files/debug/app-debug.apk 
          mv ${{ github.workspace }}/apk-files/debug/app-debug.apk ${{ github.workspace }}/apk-files/debug/app-debug-${{ steps.date.outputs.current_date_time }}.apk
         
          cp ${{ github.workspace }}/app/build/outputs/apk/release/app-release-unsigned.apk ${{ github.workspace }}/apk-files/release/app-release-unsigned.apk
          mv ${{ github.workspace }}/apk-files/release/app-release-unsigned.apk ${{ github.workspace }}/apk-files/release/app-release-unsigned-${{ steps.date.outputs.current_date_time }}.apk
      
     - name: Upload apk-files Directory
       uses: actions/upload-artifact@v3
       with:
        name: apk-files-artifactory
        path: ${{ github.workspace }}/apk-files/
        if-no-files-found: ignore
