...

- name: Set up Docker Context for Buildx
  id: buildx-context
  run: |
    docker context create builders

- name: Set up Docker Buildx
  uses: docker/setup-buildx-action@v2
  with:
    version: latest
    endpoint: builders
...
