---
name: Ansible-GitHub actions
on: push
jobs:
  repo_updated:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
    - name: Create artifact
     uses: actions/upload-artifact@v3
     with:
     name: ansible-workflow
     path: .github/workflows/main.yml
