---
name: Ansible-GitHub actions
on: push
jobs:
  repo_updated:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
  install_ansible:
    needs: repo_updated
    runs-on: self-hosted
    steps:
      - name: Installing ansible
        run: |
          sudo apt-get  update -y
          sudo apt install -y ansible
          ansible --version
          whoami
  install_ansible_lint:
    needs: repo_updated
    runs-on: self-hosted
    steps:
      - name: Installing ansible-lint
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ansible-lint
          ansible-lint --version
  run_ansible_lint:
    needs:
      - install_ansible
      - install_ansible_lint
    runs-on: self-hosted
    steps:
      - name: Linting ansible playbooks
        run: ansible-lint
  install_apache:
    needs: run_ansible_lint
    runs-on: self-hosted
    steps:
      - name: Installing apache
        run: >
          workdir="${GITHUB_WORKSPACE}"

          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u ubuntu -i $workdir/host_inventory $workdir/playbooks/apache-install.yml --private-key '/home/ubuntu/.ssh/vm-instance-key.pem'
  website-update:
    needs: install_apache
    runs-on: self-hosted
    steps:
      - name: website updating
        run: >
          workdir="${GITHUB_WORKSPACE}"

          ANSIBLE_HOST_KEY_CHECKING=False export ANSIBLE_ROLES_PATH=$workdir/roles && ansible-playbook -u ubuntu -i $workdir/host_inventory $workdir/playbooks/website-update.yml --private-key '/home/ubuntu/.ssh/vm-instance-key.pem'
  website-test:
    needs: website-update
    runs-on: self-hosted
    steps:
      - name: website testing
        run: |
          workdir="${GITHUB_WORKSPACE}"
          ANSIBLE_HOST_KEY_CHECKING=False export ANSIBLE_ROLES_PATH=$workdir/roles && ansible-playbook -u ubuntu -i $workdir/host_inventory $workdir/playbooks/website-test.yml --private-key '/home/ubuntu/.ssh/vm-instance-key.pem'

      - name: Send custom JSON data to Slack workflow
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "text": "GitHub Action pipeline result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}",
              "blocks": [
                {
                 "type": "section",
                 "text": {
                 "type": "mrkdwn",
                 "text": "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
               }
             }
            ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
  
