name: Ansible-GitHub actions
on: push
jobs:
  repo_updated:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@master
# Script to install ansible :

  install_ansible:
    needs: repo_updated
    runs-on: self-hosted
    steps:
    - name: Installing ansible 
      run: |
        sudo apt-get  update -y
        sudo apt install -y ansible
        ansible --version

# Script to install ansible-lint :

  install_ansible_lint:
    needs: repo_updated
    runs-on: self-hosted
    steps:
    - name: Installing ansible-lint
      run: |
        sudo apt-get update -y
        sudo apt-get install -y ansible-lint
        ansible-lint --version

#Script to lint ansible playbooks :

  run_ansible_lint:
    needs: [install_ansible, install_ansible_lint]
    runs-on: self-hosted
    steps:
    - name: Linting ansible playbooks
      run: ansible-lint

  install_apache:
    needs: run_ansible_lint
    runs-on: self-hosted
    steps:
    - name: Installing apache
      run: |
        workdir="${GITHUB_WORKSPACE}"
        ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -u ubuntu -i $workdir/host_inventory $workdir/playbooks/apache-install.yml --private-key '/home/ubuntu/.ssh/vm-instance-key.pem'

  website-update:
    needs: install_apache
    runs-on: self-hosted
    steps:
      - name: website updating
        run: |
          workdir="${GITHUB_WORKSPACE}"
          ANSIBLE_HOST_KEY_CHECKING=False export ANSIBLE_ROLES_PATH=$workdir/roles && ansible-playbook -u ubuntu -i $workdir/host_inventory $workdir/playbooks/website-update.yml --private-key '/home/ubuntu/.ssh/vm-instance-key.pem'
  website-test:
    needs: website-update
    runs-on: self-hosted
    steps:
      - name: website testing
        run: |
          workdir="${GITHUB_WORKSPACE}"
          ANSIBLE_HOST_KEY_CHECKING=False export ANSIBLE_ROLES_PATH=$workdir/roles && ansible-playbook -u ubuntu -i $workdir/host_inventory $workdir/playbooks/website-test.yml --private-key '/home/ubuntu/.ssh/vm-instance-key.pem'


name: Slack Notification
on:
push:
branches:
- main
jobs:
notify:
runs-on: ubuntu-latest
steps:
- name: Install dependencies
run: |
echo "Installing dependencies..."
sudo apt-get install curl
- name: Get Slack webhook URL
run: |
echo "Getting Slack webhook URL..."
SLACK_WEBHOOK_URL=$(cat .secrets/SLACK_WEBHOOK_URL)
- name: Send notification to Slack
run: |
echo "Sending notification to Slack..."
curl -X POST -H "Content-Type: application/json" -d '{"text":"New commit pushed to main!"}' $SLACK_WEBHOOK_URL
