name: Send Slack Notification
on:
  push:
    branches:
      - master
jobs:
  send-slack-notification:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@master
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y curl
      - name: Get Slack webhook URL
        run: |
          curl -s https://api.slack.com/apps/C05CE8ZD7PH/webhooks/https://hooks.slack.com/services/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
        env:
          CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
          WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Send Slack notification
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "text": "New push to main!",
            "attachments": [
              {
                "color": "#36393E",
                "title": "New push to main!",
                "text": "A new push has been made to the main branch.",
                "fields": [
                  {
                    "title": "Commit message",
                    "value": "${{ github.event.commits[0].message }}",
                    "short": true
                  }
                ]
              }
            ]
          }' ${{ secrets.SLACK_WEBHOOK_URL }}
